# -*- coding: utf-8 -*-
"""caption to image.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1rFO1H8za-rOwoRuOG3IJLaqpP55xPRWU
"""

pip install -q diffusers transformers accelerate safetensors torch pillow

from diffusers import StableDiffusionPipeline
import torch
import os

pipe = StableDiffusionPipeline.from_pretrained(
    "stabilityai/stable-diffusion-2-1",
    torch_dtype=torch.float16
)
pipe = pipe.to("cuda")

# Create folder for saving images
os.makedirs("generated_images", exist_ok=True)

prompts = [
    "A futuristic Jaipur metro station in cyberpunk style",
    "A magical forest with glowing trees at night",
    "An astronaut riding a horse in a desert",
    "A Japanese tea house on the edge of a cliff",
    "A city floating in the clouds with neon lights",
    "A bike that can fly on sky",
    "create a picture that superbikes are ready for race on track",
    "A man that can ride of tiger",
    "A birds can walk on roads",
    "A man that can adventure on mounts"
]

# Generate and save images
for i, prompt in enumerate(prompts):
    print(f" Generating: {prompt}")
    image = pipe(prompt).images[0]
    image.save(f"generated_images/image_{i+1}.png")

print(" All images saved in 'generated_images' folder.")